## Fake news classifier

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('Final.csv')
df.head()

Unnamed: 0                                              title  \
0           0  Trump on Twitter (Feb 17) - Tom Price, Boeing,...   
1           1  Putin says Russia will respond if Russian medi...   
2           2  Rosie O’Donnell Thinks Martial Law is in Order...   
3           3   Chris Christie Reportedly Told Trump To Take ...   
4           4  STATE DEPT EMPLOYEE TAPPED TO OVERSEE HILLARY ...   

                                                text          subject  \
0  The following statements were posted to the ve...     politicsNews   
1  SOCHI, Russia (Reuters) - Russian President Vl...        worldnews   
2  21st Century Wire says Arguably irrelevant Hol...      Middle-east   
3  Sources say that Chris Christie was offered se...             News   
4  You seriously can t make up this stuff State D...  Government News   

                 date  info  
0  February 17, 2017      1  
1   October 19, 2017      1  
2    January 18, 2017     0  
3   December 11, 2016     0  
4         Sep 8, 2015     0

In [7]:
df = df.sample(frac = 1).reset_index(drop = True)
df.head()

Unnamed: 0                                              title  \
0       28618   WATCH: Cop Caught On Video Body-Slamming 12-Y...   
1       37636  Florida mayors press presidential debate moder...   
2       14298  Myanmar army Facebook posts covering key perio...   
3        8239  NY court allows fraud claim against Trump Univ...   
4       18277  FULL VIDEO: THE BLOCKBUSTER INVESTIGATION INTO...   

                                                text       subject  \
0  A Texas cop is under fire after video surfaced...          News   
1  WASHINGTON (Reuters) - Mayors of 21 cities in ...  politicsNews   
2  YANGON (Reuters) - Facebook posts from Myanmar...     worldnews   
3  NEW YORK (Reuters) - Republican presidential f...  politicsNews   
4                                                        left-news   

                  date  info  
0        April 7, 2016     0  
1       March 4, 2016      1  
2  September 26, 2017      1  
3       March 1, 2016      1  
4         Apr 25, 2015     0

In [8]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [9]:
df.head()

title  \
0   WATCH: Cop Caught On Video Body-Slamming 12-Y...   
1  Florida mayors press presidential debate moder...   
2  Myanmar army Facebook posts covering key perio...   
3  NY court allows fraud claim against Trump Univ...   
4  FULL VIDEO: THE BLOCKBUSTER INVESTIGATION INTO...   

                                                text       subject  \
0  A Texas cop is under fire after video surfaced...          News   
1  WASHINGTON (Reuters) - Mayors of 21 cities in ...  politicsNews   
2  YANGON (Reuters) - Facebook posts from Myanmar...     worldnews   
3  NEW YORK (Reuters) - Republican presidential f...  politicsNews   
4                                                        left-news   

                  date  info  
0        April 7, 2016     0  
1       March 4, 2016      1  
2  September 26, 2017      1  
3       March 1, 2016      1  
4         Apr 25, 2015     0

In [10]:
X = df.drop('info', axis = 1)
y = df['info']

### text preprocessing

In [22]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [15]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
messages = X.copy()

In [24]:
corpus = []
ps = PorterStemmer()
for i in range(0 ,len(messages)) : 
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])

    review = review.lower()
    review = review.split()

    review = [ps.stem(words) for words in review if not words in stopwords.words('english')]
    review = ' '.join(review)

    corpus.append(review)

In [25]:
corpus

['watch cop caught video bodi slam year old girl',
 'florida mayor press presidenti debat moder climat airtim',
 'myanmar armi facebook post cover key period offens hidden',
 'ny court allow fraud claim trump univers proceed',
 'full video blockbust investig clinton cash',
 'ivanka fell flat face tri convinc women fall line behind dad video',
 'louisiana governor sign law make polic kill hate crime',
 'trump say work plan bring drug price',
 'nascar owner put anyon disrespect flag law enforc notic fire',
 'american airlin throw ivi leagu economist plane math',
 'dnc chair vow build parti state oop go school obama video',
 'trump right cnn fake news feder judg rule cnn fake news case may act actual malic',
 'berni sander white know like poor live ghetto video',
 'highlight trump presid april p edt gmt friday',
 'turkey erdogan say u decis jerusalem disregard unit nation',
 'taxpay paid women crush babi skull live sold lung advis obama admin healthi babi birth',
 'libertarian presidenti 

### word embedding

In [26]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [28]:
max_len = 20
vocab_size = 10000

In [30]:
one_hot_rep = [one_hot(words, vocab_size) for words in corpus]
one_hot_rep

[[1654, 2052, 9213, 769, 3048, 6127, 3110, 5340, 439],
 [5041, 2235, 4302, 8427, 3890, 9371, 3280, 9490],
 [6597, 2966, 7813, 4493, 3972, 6112, 745, 3692, 1016],
 [7404, 1655, 9143, 3374, 924, 7613, 5046, 4373],
 [2519, 769, 1700, 1326, 6099, 8495],
 [8698, 5974, 6315, 9247, 1209, 3192, 3784, 4573, 1747, 2695, 6916, 769],
 [9562, 2747, 7636, 9607, 8145, 1355, 1049, 3930, 2635],
 [7613, 7371, 1575, 6168, 6677, 9690, 2707],
 [2828, 8546, 1326, 8790, 3089, 5457, 9607, 1910, 3857, 5082],
 [9650, 8851, 3110, 1293, 6702, 6765, 415, 764],
 [3640, 3291, 8021, 7962, 6444, 5446, 8048, 320, 7171, 1431, 769],
 [7613,
  9651,
  2997,
  4291,
  7270,
  7907,
  8756,
  2604,
  2997,
  4291,
  7270,
  9222,
  7519,
  2885,
  9936,
  2340],
 [5544, 6284, 3468, 3500, 1292, 9399, 881, 1883, 769],
 [5538, 7613, 2184, 9133, 8572, 6158, 1856, 7447],
 [2603, 4175, 7371, 170, 8489, 6765, 2391, 6270, 8791],
 [4768,
  2556,
  3784,
  9625,
  6488,
  8828,
  881,
  5502,
  9430,
  7959,
  1431,
  5500,
  5970,
 

In [31]:
word_embedded = pad_sequences(one_hot_rep, maxlen = max_len, padding = 'post')
word_embedded

array([[1654, 2052, 9213, ...,    0,    0,    0],
       [5041, 2235, 4302, ...,    0,    0,    0],
       [6597, 2966, 7813, ...,    0,    0,    0],
       ...,
       [6924, 5500, 6497, ...,    0,    0,    0],
       [7292, 4097,  481, ...,    0,    0,    0],
       [1654, 3960, 1249, ...,    0,    0,    0]])

In [32]:
X_final = np.array(word_embedded)
y_final = np.array(y)

In [33]:
X_final

array([[1654, 2052, 9213, ...,    0,    0,    0],
       [5041, 2235, 4302, ...,    0,    0,    0],
       [6597, 2966, 7813, ...,    0,    0,    0],
       ...,
       [6924, 5500, 6497, ...,    0,    0,    0],
       [7292, 4097,  481, ...,    0,    0,    0],
       [1654, 3960, 1249, ...,    0,    0,    0]])

In [34]:
y_final

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

### train, test split

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, random_state = 42, test_size = 0.30)

### Building the model