## Fake news classifier

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Final.csv')
df.head()

Unnamed: 0                                              title  \
0           0  Trump on Twitter (Feb 17) - Tom Price, Boeing,...   
1           1  Putin says Russia will respond if Russian medi...   
2           2  Rosie O’Donnell Thinks Martial Law is in Order...   
3           3   Chris Christie Reportedly Told Trump To Take ...   
4           4  STATE DEPT EMPLOYEE TAPPED TO OVERSEE HILLARY ...   

                                                text          subject  \
0  The following statements were posted to the ve...     politicsNews   
1  SOCHI, Russia (Reuters) - Russian President Vl...        worldnews   
2  21st Century Wire says Arguably irrelevant Hol...      Middle-east   
3  Sources say that Chris Christie was offered se...             News   
4  You seriously can t make up this stuff State D...  Government News   

                 date  info  
0  February 17, 2017      1  
1   October 19, 2017      1  
2    January 18, 2017     0  
3   December 11, 2016     0  
4         Sep 8, 2015     0

In [3]:
df = df.sample(frac = 1).reset_index(drop = True)
df.head()

Unnamed: 0                                              title  \
0       42557  Gingrich: Trump Will Repeal 60-70% of Obama’s ...   
1       19221  U.S. signals caution to Saudis despite shared ...   
2       34131  CHOKING ON HER LIES? HILLARY CLINTON Has Cough...   
3       40338  ESPN SENIOR WRITER Says COPS, SOLDIERS Singing...   
4       31562   The RNC Pulled A Nasty Little Trick To Raise ...   

                                                text      subject  \
0  21st Century Wire says In a recent interview f...  Middle-east   
1  WASHINGTON (Reuters) - Despite President Donal...    worldnews   
2  Hillary Clinton was delivering the commencemen...    left-news   
3  What happens when a black police officer sings...     politics   
4  Donald Trump and the RNC have had a roller coa...         News   

                 date  info  
0   December 28, 2016     0  
1  November 11, 2017      1  
2        May 26, 2017     0  
3        May 30, 2016     0  
4   February 15, 2016     0

In [4]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [5]:
df.head()

title  \
0  Gingrich: Trump Will Repeal 60-70% of Obama’s ...   
1  U.S. signals caution to Saudis despite shared ...   
2  CHOKING ON HER LIES? HILLARY CLINTON Has Cough...   
3  ESPN SENIOR WRITER Says COPS, SOLDIERS Singing...   
4   The RNC Pulled A Nasty Little Trick To Raise ...   

                                                text      subject  \
0  21st Century Wire says In a recent interview f...  Middle-east   
1  WASHINGTON (Reuters) - Despite President Donal...    worldnews   
2  Hillary Clinton was delivering the commencemen...    left-news   
3  What happens when a black police officer sings...     politics   
4  Donald Trump and the RNC have had a roller coa...         News   

                 date  info  
0   December 28, 2016     0  
1  November 11, 2017      1  
2        May 26, 2017     0  
3        May 30, 2016     0  
4   February 15, 2016     0

In [6]:
X = df.drop('info', axis = 1)
y = df['info']

### text preprocessing

In [7]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [8]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
messages = X.copy()

In [11]:
corpus = []
ps = PorterStemmer()
for i in range(0 ,len(messages)) : 
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])

    review = review.lower()
    review = review.split()

    review = [ps.stem(words) for words in review if not words in stopwords.words('english')]
    review = ' '.join(review)

    corpus.append(review)

In [12]:
corpus

['gingrich trump repeal obama execut order',
 'u signal caution saudi despit share concern iran',
 'choke lie hillari clinton cough fit speech alma mater video',
 'espn senior writer say cop soldier sing ballpark racist show power say polic offic hero video',
 'rnc pull nasti littl trick rais money donald trump furiou',
 'eu u high level meet laptop ban held next week',
 'suprem court choic base sole qualif white hous',
 'berni sander show properli handl heckler trump goon interrupt ralli video',
 'bombshel women threaten hillari readi come forward sexual assault accus pervert husband video',
 'ex interpol chief say readi testifi argentina fernandez',
 'trump name assist treasuri secretari act ir chief white hous',
 'watch nc hb republican spew utterli vile lgbt hatr keep state straight video',
 'trump met airlin exec ruin meet insan unpresidenti rant video',
 'trump travel ban solid ground top court cancel hear',
 'kurdish leader depart leav nephew face reconcili',
 'colleg punish suc

### word embedding

In [13]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [14]:
max_len = 20
vocab_size = 10000

In [15]:
one_hot_rep = [one_hot(words, vocab_size) for words in corpus]
one_hot_rep

[[5646, 5088, 5137, 3745, 5473, 2912],
 [477, 1057, 3969, 9509, 7838, 7978, 3186, 7043],
 [4418, 9469, 2037, 5429, 4729, 6325, 1287, 3910, 7935, 4832],
 [6406,
  6110,
  8060,
  8216,
  3406,
  4757,
  8137,
  9477,
  3929,
  1608,
  6018,
  8216,
  7114,
  5764,
  2662,
  4832],
 [8060, 504, 2676, 3755, 7659, 9548, 7634, 9617, 5088, 7303],
 [1307, 477, 3694, 5864, 7058, 4274, 7777, 5315, 1983, 685],
 [1191, 2158, 4603, 3977, 525, 2093, 6383, 6035],
 [659, 2521, 1608, 8871, 568, 1371, 5088, 5763, 5882, 3607, 4832],
 [2062, 2348, 5765, 2037, 151, 23, 2760, 4230, 6428, 4293, 8066, 2945, 4832],
 [8702, 161, 4490, 8216, 151, 8178, 2577, 3018],
 [5088, 6951, 3463, 4506, 3026, 2747, 8994, 4490, 6383, 6035],
 [5520,
  4762,
  2661,
  7904,
  3409,
  2983,
  2153,
  9306,
  5953,
  6327,
  7476,
  8633,
  4832],
 [5088, 1502, 4729, 3815, 3772, 7058, 3873, 8676, 9251, 4832],
 [5088, 630, 7777, 2189, 5487, 5424, 2158, 1688, 781],
 [1349, 26, 1745, 8985, 6907, 1999, 2238],
 [9097, 5534, 2911, 281

In [16]:
word_embedded = pad_sequences(one_hot_rep, maxlen = max_len, padding = 'post')
word_embedded

array([[5646, 5088, 5137, ...,    0,    0,    0],
       [ 477, 1057, 3969, ...,    0,    0,    0],
       [4418, 9469, 2037, ...,    0,    0,    0],
       ...,
       [3372, 5251, 5841, ...,    0,    0,    0],
       [5088, 3935, 6422, ...,    0,    0,    0],
       [5174, 4068, 5352, ...,    0,    0,    0]])

In [17]:
X_final = np.array(word_embedded)
y_final = np.array(y)

In [18]:
X_final

array([[5646, 5088, 5137, ...,    0,    0,    0],
       [ 477, 1057, 3969, ...,    0,    0,    0],
       [4418, 9469, 2037, ...,    0,    0,    0],
       ...,
       [3372, 5251, 5841, ...,    0,    0,    0],
       [5088, 3935, 6422, ...,    0,    0,    0],
       [5174, 4068, 5352, ...,    0,    0,    0]])

In [19]:
y_final

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

### train, test split

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, random_state = 42, test_size = 0.30)

### Building the model

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, Bidirectional, LSTM, Embedding

In [23]:
model = Model()

In [33]:
model = Sequential([
    Embedding(input_dim = 10000, output_dim = 20, input_length = 20),
    Bidirectional(LSTM(128, return_sequences = True)),
    Bidirectional(LSTM(64)),
    Dense(64, activation = 'relu'),
    Dense(1, activation = 'sigmoid'),
])
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [34]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 20)            200000    
                                                                 
 bidirectional_2 (Bidirectio  (None, 20, 256)          152576    
 nal)                                                            
                                                                 
 bidirectional_3 (Bidirectio  (None, 128)              164352    
 nal)                                                            
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 525,249
Trainable params: 525,249
Non-tr

### training the model

In [35]:
model.fit(X_train, y_train, epochs = 10, batch_size = 128, validation_split = 0.20)

Epoch 1/10
197/197 [==============================] - 24s 98ms/step - loss: 0.2330 - accuracy: 0.8994 - val_loss: 0.1433 - val_accuracy: 0.9470
Epoch 2/10
197/197 [==============================] - 17s 85ms/step - loss: 0.1060 - accuracy: 0.9607 - val_loss: 0.1362 - val_accuracy: 0.9499
Epoch 3/10
197/197 [==============================] - 17s 87ms/step - loss: 0.0712 - accuracy: 0.9754 - val_loss: 0.1655 - val_accuracy: 0.9485
Epoch 4/10
197/197 [==============================] - 17s 87ms/step - loss: 0.0516 - accuracy: 0.9823 - val_loss: 0.1728 - val_accuracy: 0.9472
Epoch 5/10
197/197 [==============================] - 18s 89ms/step - loss: 0.0406 - accuracy: 0.9864 - val_loss: 0.1739 - val_accuracy: 0.9488
Epoch 6/10
197/197 [==============================] - 18s 90ms/step - loss: 0.0337 - accuracy: 0.9886 - val_loss: 0.2005 - val_accuracy: 0.9469
Epoch 7/10
197/197 [==============================] - 18s 91ms/step - loss: 0.0232 - accuracy: 0.9927 - val_loss: 0.2280 - val_accuracy:

### predictions

In [36]:
y_pred = model.predict(X_test)

421/421 [==============================] - 5s 9ms/step


In [37]:
y_pred

array([[9.9928927e-01],
       [9.9926043e-01],
       [1.3446954e-07],
       ...,
       [5.1641013e-07],
       [9.9935198e-01],
       [3.0242575e-03]], dtype=float32)

In [38]:
y_pred = (y_pred > 0.5).astype(int)

In [39]:
y_pred

array([[1],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [40]:
y_test

array([1, 1, 0, ..., 0, 1, 1], dtype=int64)

In [41]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(accuracy_score(y_pred, y_test))
print(confusion_matrix(y_pred, y_test))
print(classification_report(y_pred, y_test))

0.9348923533778768
[[6705  511]
 [ 366 5888]]
              precision    recall  f1-score   support

           0       0.95      0.93      0.94      7216
           1       0.92      0.94      0.93      6254

    accuracy                           0.93     13470
   macro avg       0.93      0.94      0.93     13470
weighted avg       0.94      0.93      0.93     13470

