## Infrence models

### Data loading

In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'fra.txt'
eng_texts, fra_texts = [], []
num_samples = 10000

In [3]:
with open (path, 'r', encoding = 'UTF-8') as f :
    lines = f.read().split('\n')

    for line in lines[:num_samples] :
        eng_words, fra_words = line.split('\t')[:2]
        fra_words = '\t' + fra_words + '\n'

        eng_texts.append(eng_words)
        fra_texts.append(fra_words)

In [4]:
eng_texts

['Go.',
 'Go.',
 'Go.',
 'Go.',
 'Hi.',
 'Hi.',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Who?',
 'Wow!',
 'Wow!',
 'Wow!',
 'Duck!',
 'Duck!',
 'Duck!',
 'Fire!',
 'Help!',
 'Hide.',
 'Hide.',
 'Jump!',
 'Jump.',
 'Stop!',
 'Stop!',
 'Stop!',
 'Wait!',
 'Wait!',
 'Wait!',
 'Wait.',
 'Wait.',
 'Wait.',
 'Wait.',
 'Begin.',
 'Begin.',
 'Go on.',
 'Go on.',
 'Go on.',
 'Hello!',
 'Hello!',
 'Hello.',
 'Hello.',
 'Hello.',
 'Hello.',
 'I see.',
 'I see.',
 'I try.',
 'I won!',
 'I won!',
 'I won.',
 'Oh no!',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Shoot!',
 'Shoot!',
 'Smile.',
 'Smile.',
 'Smile.',
 'Sorry?',
 'Attack!',
 'Attack!',
 'Attack!',
 'Attack!',
 'Buy it.',
 'Buy it.',
 'Buy it.',
 'Buy it.',
 'Cheers!',
 'Cheers!',
 'Cheers!',
 'Cheers!',
 'Eat it.',
 'Eat it.',
 'Exhale.',
 'Get 

In [5]:
fra_texts

['\tVa !\n',
 '\tMarche.\n',
 '\tEn route !\n',
 '\tBouge !\n',
 '\tSalut !\n',
 '\tSalut.\n',
 '\tCours\u202f!\n',
 '\tCourez\u202f!\n',
 '\tPrenez vos jambes à vos cous !\n',
 '\tFile !\n',
 '\tFilez !\n',
 '\tCours !\n',
 '\tFuyez !\n',
 '\tFuyons !\n',
 '\tCours\u202f!\n',
 '\tCourez\u202f!\n',
 '\tPrenez vos jambes à vos cous !\n',
 '\tFile !\n',
 '\tFilez !\n',
 '\tCours !\n',
 '\tFuyez !\n',
 '\tFuyons !\n',
 '\tQui ?\n',
 '\tÇa alors\u202f!\n',
 '\tWaouh\xa0!\n',
 '\tWah\xa0!\n',
 '\tÀ terre\xa0!\n',
 '\tBaisse-toi\xa0!\n',
 '\tBaissez-vous\xa0!\n',
 '\tAu feu !\n',
 "\tÀ l'aide !\n",
 '\tCache-toi.\n',
 '\tCachez-vous.\n',
 '\tSaute.\n',
 '\tSaute.\n',
 '\tÇa suffit\u202f!\n',
 '\tStop\u202f!\n',
 '\tArrête-toi !\n',
 '\tAttends !\n',
 '\tAttendez !\n',
 '\tAttendez.\n',
 '\tAttends !\n',
 '\tAttendez !\n',
 '\tAttends.\n',
 '\tAttendez.\n',
 '\tCommencez.\n',
 '\tCommence.\n',
 '\tPoursuis.\n',
 '\tContinuez.\n',
 '\tPoursuivez.\n',
 '\tBonjour !\n',
 '\tSalut !\n',
 '\tBonjo

### Data prep

In [5]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [6]:
max_eng_word = max([len(word) for word in eng_texts])
max_fra_word = max([len(word) for word in fra_texts])
print(f"{max_eng_word} :: {max_fra_word}")

14 :: 59


In [7]:
eng_tok = Tokenizer(filters = ' ', lower = True)
eng_tok.fit_on_texts(eng_texts)
encoder_input_data = eng_tok.texts_to_sequences(eng_texts)
encoder_input_data = pad_sequences(encoder_input_data, maxlen = max_eng_word, padding = 'pre')

In [9]:
encoder_input_data

array([[  0,   0,   0, ...,   0,   0,  30],
       [  0,   0,   0, ...,   0,   0,  30],
       [  0,   0,   0, ...,   0,   0,  30],
       ...,
       [  0,   0,   0, ...,  10, 207, 436],
       [  0,   0,   0, ...,  10, 207, 261],
       [  0,   0,   0, ...,  10, 207, 200]])

In [8]:
fra_tok = Tokenizer(filters = ' ', lower = True)
fra_tok.fit_on_texts(fra_texts)
decoder_input_data = fra_tok.texts_to_sequences(fra_texts)
decoder_input_data = pad_sequences(decoder_input_data, maxlen = max_fra_word, padding = 'pre')

In [9]:
decoder_input_data

array([[   0,    0,    0, ...,    0,   92,    2],
       [   0,    0,    0, ...,    0,    0,  991],
       [   0,    0,    0, ...,  145,  334,    2],
       ...,
       [   0,    0,    0, ...,   20, 5804,  380],
       [   0,    0,    0, ...,   20, 5805,  380],
       [   0,    0,    0, ..., 2286,  893,  456]])

In [10]:
decoder_target_data = np.zeros_like(decoder_input_data)
decoder_target_data[:, :-1] = decoder_input_data[:, 1:]
decoder_target_data

array([[   0,    0,    0, ...,   92,    2,    0],
       [   0,    0,    0, ...,    0,  991,    0],
       [   0,    0,    0, ...,  334,    2,    0],
       ...,
       [   0,    0,    0, ..., 5804,  380,    0],
       [   0,    0,    0, ..., 5805,  380,    0],
       [   0,    0,    0, ...,  893,  456,    0]])

In [11]:
print(f"{encoder_input_data.shape} :: {decoder_input_data.shape} :: {decoder_target_data.shape}")

(10000, 14) :: (10000, 59) :: (10000, 59)


### vocabs

In [12]:
eng_vocabs = len(eng_tok.word_index) + 1
fra_vocabs = len(fra_tok.word_index) + 1

In [13]:
print(f"{eng_vocabs} :: {fra_vocabs}")

2707 :: 5806


### making the encoders

In [14]:
from tensorflow.keras.layers import Input, Embedding, LSTM

In [15]:
latent_dim = 256

In [16]:
enc_inputs = Input(shape = (max_eng_word, ))
enc_emb = Embedding(eng_vocabs, latent_dim)(enc_inputs)
enc_lstm = LSTM(latent_dim, return_state = True, return_sequences = True)
enc_outputs, state_h, state_c = enc_lstm(enc_emb)

### making the decoders

In [17]:
dec_inputs = Input(shape = (max_fra_word))
dec_emb_layer = Embedding(fra_vocabs, latent_dim)
dec_emb = dec_emb_layer(dec_inputs)
dec_lstm = LSTM(latent_dim, return_state = True, return_sequences = True)

### building the final Bahdanau attention model

In [18]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Concatenate, Dense

In [19]:
class BahdanauAttention(Layer) : 
    def __init__(self, units) :
        super(BahdanauAttention, self).__init__()
        self.W1 = Dense(units)
        self.W2 = Dense(units)
        self.V = Dense(1)

    def call(self, query, values) :
        query_wuth_time_axis = tensorflow.expand_dims(query, 1)
        score = self.V(tensorflow.nn.tanh(self.W1(values)) + self.W2(query_wuth_time_axis))
        attention_weights = tensorflow.nn.softmax(score, 1)
        context_vector = attention_weights * score
        context_vector = tensorflow.reduce_sum(context_vector, 1)

        return context_vector, attention_weights

In [20]:
attention = BahdanauAttention(latent_dim)
all_outputs = []
decoder_state_h, decoder_state_c = state_h, state_c
for t in range(max_fra_word) : 
    context_vector, _ = attention(decoder_state_h, decoder_state_c)
    X = tensorflow.expand_dims(dec_emb[:, t], 1)
    X = Concatenate(axis = -1)([context_vector[:, None, :], X])
    outputs, decoder_state_h, decoder_state_c = dec_lstm(X, initial_state = [decoder_state_h, decoder_state_c])
    outputs = Dense(fra_vocabs, activation = 'softmax')(outputs)
    all_outputs.append(outputs)

dec_outputs = tensorflow.concat(all_outputs, 1)

### main model and training

In [21]:
model = Model()

In [22]:
model = Model([enc_inputs, dec_inputs], dec_outputs)
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [23]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 14)]         0           []                               
                                                                                                  
 embedding (Embedding)          (None, 14, 256)      692992      ['input_1[0][0]']                
                                                                                                  
 input_2 (InputLayer)           [(None, 59)]         0           []                               
                                                                                                  
 lstm (LSTM)                    [(None, 14, 256),    525312      ['embedding[0][0]']              
                                 (None, 256),                                               

In [24]:
model.fit(
    [encoder_input_data, decoder_input_data],
    np.expand_dims(decoder_target_data, -1),
    batch_size = 128,
    epochs = 1,
    validation_split = 0.2
)

63/63 [==============================] - 312s 3s/step - loss: 2.5378 - accuracy: 0.8758 - val_loss: 0.4272 - val_accuracy: 0.9420


## Inference models

### reverse indexing

In [26]:
reverse_eng_tokens = {i : w for w, i in eng_tok.word_index.items()}
reverse_fra_tokens = {i : w for w, i in fra_tok.word_index.items()}

In [27]:
reverse_eng_tokens

{1: 'i',
 2: "i'm",
 3: 'tom',
 4: 'is',
 5: 'a',
 6: 'it',
 7: 'you',
 8: 'it.',
 9: "it's",
 10: 'we',
 11: 'was',
 12: 'be',
 13: 'are',
 14: 'he',
 15: 'me.',
 16: 'get',
 17: 'you.',
 18: "don't",
 19: "you're",
 20: 'tom.',
 21: 'go',
 22: 'they',
 23: 'up.',
 24: 'can',
 25: 'do',
 26: "i'll",
 27: 'take',
 28: 'let',
 29: 'to',
 30: 'go.',
 31: "that's",
 32: 'the',
 33: 'have',
 34: 'this',
 35: 'keep',
 36: 'got',
 37: 'me',
 38: "they're",
 39: 'not',
 40: "we're",
 41: 'need',
 42: 'did',
 43: "tom's",
 44: 'stay',
 45: 'my',
 46: 'come',
 47: 'no',
 48: 'am',
 49: 'she',
 50: "let's",
 51: 'that.',
 52: 'who',
 53: 'like',
 54: "he's",
 55: 'stop',
 56: 'this.',
 57: 'him.',
 58: 'saw',
 59: 'here.',
 60: 'that',
 61: 'love',
 62: 'how',
 63: 'us.',
 64: 'all',
 65: 'feel',
 66: 'must',
 67: 'what',
 68: 'look',
 69: 'out.',
 70: 'want',
 71: 'it?',
 72: 'in.',
 73: 'felt',
 74: "can't",
 75: 'just',
 76: 'lost.',
 77: 'see',
 78: 'home.',
 79: 'one.',
 80: 'try',
 81: 'pl

In [28]:
reverse_fra_tokens

{1: '\tje',
 2: '!\n',
 3: 'suis',
 4: '\ttom',
 5: '?\n',
 6: "\tc'est",
 7: 'est',
 8: 'de',
 9: '\til',
 10: "\tj'ai",
 11: 'pas',
 12: '\tnous',
 13: 'le',
 14: 'à',
 15: 'me',
 16: 'a',
 17: 'la',
 18: 'un',
 19: 'en',
 20: 'ne',
 21: 'vous',
 22: 'tom.\n',
 23: '\tvous',
 24: '\ttu',
 25: 'une',
 26: '\tne',
 27: '\test-ce',
 28: 'les',
 29: 'sont',
 30: '\tils',
 31: 'nous',
 32: 'que',
 33: '\tça',
 34: '\tsoyez',
 35: 'fait',
 36: 'pas.\n',
 37: 'sommes',
 38: 'êtes',
 39: '\telles',
 40: '\telle',
 41: '\tqui',
 42: 'ça.\n',
 43: 'des',
 44: 'été',
 45: 'es',
 46: 'te',
 47: 'tom',
 48: 'du',
 49: 'faut',
 50: '\tsois',
 51: 'y',
 52: '\têtes-vous',
 53: 'bien.\n',
 54: '\ton',
 55: 'ai',
 56: 'se',
 57: '\trestez',
 58: "m'a",
 59: "l'ai",
 60: "\tj'aime",
 61: 'besoin',
 62: 'était',
 63: 'peux',
 64: '\tce',
 65: '\treste',
 66: 'avons',
 67: "n'est",
 68: "\tj'étais",
 69: "s'est",
 70: 'va',
 71: 'ça',
 72: "\tc'était",
 73: "c'est",
 74: 'moi.\n',
 75: 'ont',
 76: 'alle

In [29]:
print(f"{len(reverse_eng_tokens)} :: {len(reverse_fra_tokens)}")

2706 :: 5805


In [30]:
target_word_index = fra_tok.word_index

In [32]:
len(target_word_index)

5805

### encoders

In [33]:
enc_model = Model(enc_inputs, [enc_outputs, state_h, state_c])

### decoders