## Infrence models

### Data loading

In [1]:
import pandas as pd
import numpy as np

In [98]:
path = 'fra.txt'
eng_texts, fra_texts = [], []
num_samples = 10000

In [99]:
with open (path, 'r', encoding = 'UTF-8') as f :
    lines = f.read().split('\n')

    for line in lines[:num_samples] :
        eng_words, fra_words = line.split('\t')[:2]

        eng_words = eng_words.strip()
        fra_words = '<sos> ' + fra_words.strip() + ' <eos>'

        eng_texts.append(eng_words)
        fra_texts.append(fra_words)

In [100]:
eng_texts

['Go.',
 'Go.',
 'Go.',
 'Go.',
 'Hi.',
 'Hi.',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run!',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Run.',
 'Who?',
 'Wow!',
 'Wow!',
 'Wow!',
 'Duck!',
 'Duck!',
 'Duck!',
 'Fire!',
 'Help!',
 'Hide.',
 'Hide.',
 'Jump!',
 'Jump.',
 'Stop!',
 'Stop!',
 'Stop!',
 'Wait!',
 'Wait!',
 'Wait!',
 'Wait.',
 'Wait.',
 'Wait.',
 'Wait.',
 'Begin.',
 'Begin.',
 'Go on.',
 'Go on.',
 'Go on.',
 'Hello!',
 'Hello!',
 'Hello.',
 'Hello.',
 'Hello.',
 'Hello.',
 'I see.',
 'I see.',
 'I try.',
 'I won!',
 'I won!',
 'I won.',
 'Oh no!',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Relax.',
 'Shoot!',
 'Shoot!',
 'Smile.',
 'Smile.',
 'Smile.',
 'Sorry?',
 'Attack!',
 'Attack!',
 'Attack!',
 'Attack!',
 'Buy it.',
 'Buy it.',
 'Buy it.',
 'Buy it.',
 'Cheers!',
 'Cheers!',
 'Cheers!',
 'Cheers!',
 'Eat it.',
 'Eat it.',
 'Exhale.',
 'Get 

In [101]:
fra_texts

['<sos> Va ! <eos>',
 '<sos> Marche. <eos>',
 '<sos> En route ! <eos>',
 '<sos> Bouge ! <eos>',
 '<sos> Salut ! <eos>',
 '<sos> Salut. <eos>',
 '<sos> Cours\u202f! <eos>',
 '<sos> Courez\u202f! <eos>',
 '<sos> Prenez vos jambes à vos cous ! <eos>',
 '<sos> File ! <eos>',
 '<sos> Filez ! <eos>',
 '<sos> Cours ! <eos>',
 '<sos> Fuyez ! <eos>',
 '<sos> Fuyons ! <eos>',
 '<sos> Cours\u202f! <eos>',
 '<sos> Courez\u202f! <eos>',
 '<sos> Prenez vos jambes à vos cous ! <eos>',
 '<sos> File ! <eos>',
 '<sos> Filez ! <eos>',
 '<sos> Cours ! <eos>',
 '<sos> Fuyez ! <eos>',
 '<sos> Fuyons ! <eos>',
 '<sos> Qui ? <eos>',
 '<sos> Ça alors\u202f! <eos>',
 '<sos> Waouh\xa0! <eos>',
 '<sos> Wah\xa0! <eos>',
 '<sos> À terre\xa0! <eos>',
 '<sos> Baisse-toi\xa0! <eos>',
 '<sos> Baissez-vous\xa0! <eos>',
 '<sos> Au feu ! <eos>',
 "<sos> À l'aide ! <eos>",
 '<sos> Cache-toi. <eos>',
 '<sos> Cachez-vous. <eos>',
 '<sos> Saute. <eos>',
 '<sos> Saute. <eos>',
 '<sos> Ça suffit\u202f! <eos>',
 '<sos> Stop\u202

### Data prep

In [91]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [102]:
max_eng_word = max([len(word) for word in eng_texts])
max_fra_word = max([len(word) for word in fra_texts])
print(f"{max_eng_word} :: {max_fra_word}")

14 :: 69


In [103]:
eng_tok = Tokenizer(filters = ' ', lower = True)
eng_tok.fit_on_texts(eng_texts)
encoder_input_data = eng_tok.texts_to_sequences(eng_texts)
encoder_input_data = pad_sequences(encoder_input_data, maxlen = max_eng_word, padding = 'pre')

In [104]:
encoder_input_data

array([[  0,   0,   0, ...,   0,   0,  30],
       [  0,   0,   0, ...,   0,   0,  30],
       [  0,   0,   0, ...,   0,   0,  30],
       ...,
       [  0,   0,   0, ...,  10, 207, 436],
       [  0,   0,   0, ...,  10, 207, 261],
       [  0,   0,   0, ...,  10, 207, 200]])

In [105]:
fra_tok = Tokenizer(filters = ' ', lower = True)
fra_tok.fit_on_texts(fra_texts)
decoder_input_data = fra_tok.texts_to_sequences(fra_texts)
decoder_input_data = pad_sequences(decoder_input_data, maxlen = max_fra_word, padding = 'pre')

In [106]:
decoder_input_data

array([[   0,    0,    0, ...,   42,    4,    2],
       [   0,    0,    0, ...,    1,  430,    2],
       [   0,    0,    0, ...,  326,    4,    2],
       ...,
       [   0,    0,    0, ..., 5570,  369,    2],
       [   0,    0,    0, ..., 5571,  369,    2],
       [   0,    0,    0, ...,  517,  446,    2]])

In [107]:
fra_tok.word_index.keys()

dict_keys(['<sos>', '<eos>', 'je', '!', 'tom', 'suis', '?', "c'est", 'est', 'nous', 'de', 'il', "j'ai", 'ne', 'pas', 'le', 'vous', 'à', 'me', 'la', 'a', 'un', 'en', 'tu', 'les', 'tom.', 'ça', 'une', 'est-ce', 'sont', 'ils', 'qui', 'que', 'soyez', 'fait', 'pas.', 'sommes', 'êtes', 'elles', 'du', 'elle', 'va', 'des', 'ça.', 'te', 'sois', 'été', 'es', 'ce', 'faut', 'y', 'êtes-vous', 'fais', 'bien.', 'on', 'ai', 'se', 'tout', 'restez', "m'a", 'besoin', "l'ai", "j'aime", 'reste', 'était', 'peux', 'avons', "n'est", "j'étais", 'mon', "s'est", "c'était", 'au', 'sens', 'es-tu', 'bien', 'moi.', 'ont', 'aller.', 'partir.', 'ici.', 'prends', 'faites', 'veux', 'arrête', 'j’ai', 'vais', "j'en", 'train', 'chez', 'est-il', "s'il", 'prenez', "m'en", 'arrêtez', "l'a", 'personne', 'mal.', 'dois', "j'adore", 'avec', 'cela', "l'air", 'trop', 'moi', 'comme', 'suis-je', 'triste.', 'ton', 'quelle', 'toi.', 'ma', 'plaît.', 'calme.', 'ceci.', 'comment', 'as', 'très', "d'un", 'maintenant.', 'là.', 'allez', 'plus

In [108]:
decoder_target_data = np.zeros_like(decoder_input_data)
decoder_target_data[:, :-1] = decoder_input_data[:, 1:]
decoder_target_data

array([[  0,   0,   0, ...,   4,   2,   0],
       [  0,   0,   0, ..., 430,   2,   0],
       [  0,   0,   0, ...,   4,   2,   0],
       ...,
       [  0,   0,   0, ..., 369,   2,   0],
       [  0,   0,   0, ..., 369,   2,   0],
       [  0,   0,   0, ..., 446,   2,   0]])

In [109]:
print(f"{encoder_input_data.shape} :: {decoder_input_data.shape} :: {decoder_target_data.shape}")

(10000, 14) :: (10000, 69) :: (10000, 69)


### vocabs

In [110]:
eng_vocabs = len(eng_tok.word_index) + 1
fra_vocabs = len(fra_tok.word_index) + 1

In [111]:
print(f"{eng_vocabs} :: {fra_vocabs}")

2707 :: 5572


### making the encoders

In [63]:
from tensorflow.keras.layers import Input, Embedding, LSTM

In [64]:
latent_dim = 256

In [112]:
enc_inputs = Input(shape = (max_eng_word, ))
enc_emb = Embedding(eng_vocabs, latent_dim)(enc_inputs)
enc_lstm = LSTM(latent_dim, return_state = True, return_sequences = True)
enc_outputs, state_h, state_c = enc_lstm(enc_emb)

### making the decoders

In [113]:
dec_inputs = Input(shape = (max_fra_word))
dec_emb_layer = Embedding(fra_vocabs, latent_dim)
dec_emb = dec_emb_layer(dec_inputs)
dec_lstm = LSTM(latent_dim, return_state = True, return_sequences = True)

### building the final Bahdanau attention model

In [67]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Concatenate, Dense

In [114]:
class BahdanauAttention(Layer) : 
    def __init__(self, units) :
        super(BahdanauAttention, self).__init__()
        self.W1 = Dense(units)
        self.W2 = Dense(units)
        self.V = Dense(1)

    def call(self, query, values) :
        query_wuth_time_axis = tensorflow.expand_dims(query, 1)
        score = self.V(tensorflow.nn.tanh(self.W1(values)) + self.W2(query_wuth_time_axis))
        attention_weights = tensorflow.nn.softmax(score, 1)
        context_vector = attention_weights * score
        context_vector = tensorflow.reduce_sum(context_vector, 1)

        return context_vector, attention_weights

In [115]:
attention = BahdanauAttention(latent_dim)
all_outputs = []
decoder_state_h, decoder_state_c = state_h, state_c
for t in range(max_fra_word) : 
    context_vector, _ = attention(decoder_state_h, decoder_state_c)
    X = tensorflow.expand_dims(dec_emb[:, t], 1)
    X = Concatenate(axis = -1)([context_vector[:, None, :], X])
    outputs, decoder_state_h, decoder_state_c = dec_lstm(X, initial_state = [decoder_state_h, decoder_state_c])
    outputs = Dense(fra_vocabs, activation = 'softmax')(outputs)
    all_outputs.append(outputs)

dec_outputs = tensorflow.concat(all_outputs, 1)

### main model and training

In [116]:
model = Model()

In [117]:
model = Model([enc_inputs, dec_inputs], dec_outputs)
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [118]:
model.summary()

Model: "model_9"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_13 (InputLayer)          [(None, 14)]         0           []                               
                                                                                                  
 embedding_4 (Embedding)        (None, 14, 256)      692992      ['input_13[0][0]']               
                                                                                                  
 input_14 (InputLayer)          [(None, 69)]         0           []                               
                                                                                                  
 lstm_4 (LSTM)                  [(None, 14, 256),    525312      ['embedding_4[0][0]']            
                                 (None, 256),                                               

In [119]:
model.fit(
    [encoder_input_data, decoder_input_data],
    np.expand_dims(decoder_target_data, -1),
    batch_size = 128,
    epochs = 1,
    validation_split = 0.2
)

63/63 [==============================] - 392s 4s/step - loss: 2.4929 - accuracy: 0.8760 - val_loss: 0.3807 - val_accuracy: 0.9416


## Inference models

### reverse indexing

In [120]:
reverse_eng_tokens = {i : w for w, i in eng_tok.word_index.items()}
reverse_fra_tokens = {i : w for w, i in fra_tok.word_index.items()}

In [121]:
reverse_eng_tokens

{1: 'i',
 2: "i'm",
 3: 'tom',
 4: 'is',
 5: 'a',
 6: 'it',
 7: 'you',
 8: 'it.',
 9: "it's",
 10: 'we',
 11: 'was',
 12: 'be',
 13: 'are',
 14: 'he',
 15: 'me.',
 16: 'get',
 17: 'you.',
 18: "don't",
 19: "you're",
 20: 'tom.',
 21: 'go',
 22: 'they',
 23: 'up.',
 24: 'can',
 25: 'do',
 26: "i'll",
 27: 'take',
 28: 'let',
 29: 'to',
 30: 'go.',
 31: "that's",
 32: 'the',
 33: 'have',
 34: 'this',
 35: 'keep',
 36: 'got',
 37: 'me',
 38: "they're",
 39: 'not',
 40: "we're",
 41: 'need',
 42: 'did',
 43: "tom's",
 44: 'stay',
 45: 'my',
 46: 'come',
 47: 'no',
 48: 'am',
 49: 'she',
 50: "let's",
 51: 'that.',
 52: 'who',
 53: 'like',
 54: "he's",
 55: 'stop',
 56: 'this.',
 57: 'him.',
 58: 'saw',
 59: 'here.',
 60: 'that',
 61: 'love',
 62: 'how',
 63: 'us.',
 64: 'all',
 65: 'feel',
 66: 'must',
 67: 'what',
 68: 'look',
 69: 'out.',
 70: 'want',
 71: 'it?',
 72: 'in.',
 73: 'felt',
 74: "can't",
 75: 'just',
 76: 'lost.',
 77: 'see',
 78: 'home.',
 79: 'one.',
 80: 'try',
 81: 'pl

In [122]:
reverse_fra_tokens

{1: '<sos>',
 2: '<eos>',
 3: 'je',
 4: '!',
 5: 'tom',
 6: 'suis',
 7: '?',
 8: "c'est",
 9: 'est',
 10: 'nous',
 11: 'de',
 12: 'il',
 13: "j'ai",
 14: 'ne',
 15: 'pas',
 16: 'le',
 17: 'vous',
 18: 'à',
 19: 'me',
 20: 'la',
 21: 'a',
 22: 'un',
 23: 'en',
 24: 'tu',
 25: 'les',
 26: 'tom.',
 27: 'ça',
 28: 'une',
 29: 'est-ce',
 30: 'sont',
 31: 'ils',
 32: 'qui',
 33: 'que',
 34: 'soyez',
 35: 'fait',
 36: 'pas.',
 37: 'sommes',
 38: 'êtes',
 39: 'elles',
 40: 'du',
 41: 'elle',
 42: 'va',
 43: 'des',
 44: 'ça.',
 45: 'te',
 46: 'sois',
 47: 'été',
 48: 'es',
 49: 'ce',
 50: 'faut',
 51: 'y',
 52: 'êtes-vous',
 53: 'fais',
 54: 'bien.',
 55: 'on',
 56: 'ai',
 57: 'se',
 58: 'tout',
 59: 'restez',
 60: "m'a",
 61: 'besoin',
 62: "l'ai",
 63: "j'aime",
 64: 'reste',
 65: 'était',
 66: 'peux',
 67: 'avons',
 68: "n'est",
 69: "j'étais",
 70: 'mon',
 71: "s'est",
 72: "c'était",
 73: 'au',
 74: 'sens',
 75: 'es-tu',
 76: 'bien',
 77: 'moi.',
 78: 'ont',
 79: 'aller.',
 80: 'partir.',


In [123]:
print(f"{len(reverse_eng_tokens)} :: {len(reverse_fra_tokens)}")

2706 :: 5571


In [78]:
target_word_index = fra_tok.word_index

In [79]:
len(target_word_index)

5805

### encoders

In [124]:
enc_model = Model(enc_inputs, [enc_outputs, state_h, state_c])

### decoders

In [125]:
decoder_state_input_h = Input(shape = (latent_dim, ))
decoder_state_input_c = Input(shape = (latent_dim, ))
encoder_outputs_inputs = Input(shape = (max_eng_word, latent_dim))
decoder_input_single = Input(shape = (1, ))
decoder_emb_2 = dec_emb_layer(decoder_input_single)
context_vector, attention_weights = attention(decoder_state_input_h, encoder_outputs_inputs)
X = Concatenate(axis = -1)([tensorflow.expand_dims(context_vector, 1), decoder_emb_2])
decoder_outputs, state_h_inf, state_c_inf = dec_lstm(X, initial_state = [decoder_state_input_h, decoder_state_input_c])
decoder_outputs = Dense(fra_vocabs, activation = 'softmax')(decoder_outputs)

dec_model = Model(
    [decoder_input_single, decoder_state_input_h, decoder_state_input_c, encoder_outputs_inputs],
    [decoder_outputs, state_h_inf, state_c_inf, attention_weights]
)

### final decode sequence function

In [128]:
def decode_sequence(input_seq) : 
    enc_outs, state_h, state_c = enc_model.predict(input_seq)

    target_seq = np.array([[fra_tok.word_index['<sos>']]])
    
    stop_condition = False
    decode_sentence = []

    while not stop_condition :
        output_tokens, h, c, attn = dec_model.predict([target_seq, state_h, state_c, enc_outs])

        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_word = reverse_fra_tokens.get(sampled_token_index, '')

        if (sampled_word == '<eos>' or len(decode_sentence) > max_fra_word) :
            stop_condition = True
        else :
            decode_sentence.append(sampled_word)

        target_seq = np.array([[sampled_token_index]])

        state_h, state_c = h, c

    return ' '.join(decode_sentence)

### Batch testing

In [130]:
# for i in range(10) : 
#     input_seq = encoder_input_data[i : i+1]
#     decoded_sentences = decode_sequence(input_seq)
#     print(f"english words : {eng_texts[i]}")
#     print(f"french words : {decoded_sentences}")
#     print('-'*30)